name: Build and push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tts:
    runs-on: self-hosted
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3

      - run: |
          docker build -f ./Dockerfile.amd64 \
          -t satont/twir-tts:latest \
          --cache-from type=gha,scope=twir-tts \
          --cache-to type=gha,mode=max,scope=twir-tts .

          docker push satont/twir-tts:latest